name: example
description: A project that showcases how to enable the recommended lints for BlackPaws Flutter apps.

publish_to: none

environment:
  sdk: ^3.8.0

# Add the latest version of `package:blackpaws_flutter_lint` as a dev_dependency. The
# lint set provided by this package is activated in the `analysis_options.yaml`
# file located next to this `pubspec.yaml` file.
dev_dependencies:
  blackpaws_flutter_lint: ^6.0.0 # Check https://pub.dev/packages/blackpaws_flutter_lint for latest version number.
